version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install --save-dev @angular-devkit/build-angular
      - npm install -g @angular/cli@6.1.0
  build:
    commands:
      - ng build --configuration=$BUILD_ENV --build-optimizer
  post_build:
    commands:
      - aws s3 sync dist/ s3://$BUCKET_NAME --delete
