version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install --save-dev @angular-devkit/build-angular
      - npm install -g @angular/cli@6.1.0
  build:
    commands:
      - ng b --prod --aot=false --build-optimizer=false
  post_build:
    commands:
      - aws s3 sync . s3://jlnabors3 --delete
